#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor eDP -d 1 2 3 4 5 6 7 8 9

for desktop in $(bspc query --monitors --names)
do
	bspc monitor $desktop -d 1 2 3 4 5 6 7 8 9
done


# Window style
bspc config border_width         3
bspc config window_gap           5
bspc config normal_border_color  \#282828
bspc config active_border_color  \#a89984
bspc config focused_border_color \#ebdbb2

# Just because i got used to dwm ¯\_(ツ)_/¯
bspc config click_to_focus        none
bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      treu

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mpv state=floating

emacs --daemon &
picom &
~/.config/bspwm/launch_polybar.sh &
feh --bg-scale ~/Pictures/wallpapers/tinta.jpg &
setxkbmap -option "caps:ctrl_modifier" &
dunst &
xsetroot -cursor_name left_ptr &
kanata -c ~/.config/kanata/config.kbd &
nm-applet &
#clight --no-backlight --no-screen --lat="-19.91" --lon="-43.93" &
redshift -l '-19.91:-43.93' &
