;;; Automatically generated by ‘recentf’ on Mon Nov  1 11:55:51 2021.

(setq recentf-list
      '(
        "/home/basqs/.emacs.d/var/elfeed/db/index"
        "/home/basqs/.emacs.d/emacs.org"
        "/home/basqs/Documents/org/org-agenda.org"
        "/home/basqs/.config/nixpkgs/emacs.nix"
        "/home/basqs/.config/nixpkgs/home.nix"
        "/home/basqs/.config/nixpkgs/git.nix"
        "/home/basqs/Documents/git/nixfiles/README.org"
        "/home/basqs/.config/xmonad/xmobar.hs"
        "/home/basqs/.config/xmonad/xmonad.hs"
        "/home/basqs/.config/nixpkgs/init.vim"
        "/etc/nixos/configuration.nix"
        "/home/basqs/.config/nixpkgs/xmonad.nix"
        "/home/basqs/.config/nixpkgs/alacritty.nix"
        "/home/basqs/Projects/git/dwm/config.h"
        "/home/basqs/.config/rofi/config.rasi"
        "/home/basqs/.config/bookmarks"
        "/home/basqs/Projects/emacs-from-scratch/Emacs.org"
        "/home/basqs/Documents/org/book.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
