conky -c ~/.config/conky/conky.lua | while read -r; do xsetroot -name "$REPLY"; done &
xsetroot -cursor_name left_ptr &
setxkbmap br -option caps:swapescape &
transmission-daemon  &
xrdb ~/.Xresources &
sxhkd &
dunst &
redshift -l -19.5515:-43.5616 &
sleep 1; xwallpaper --zoom ~/Pictures/wallpapers/tomorrow.png &
exec dwm
