;;; Automatically generated by ‘recentf’ on Wed Feb  2 22:07:58 2022.

(setq recentf-list
      '(
        "/home/basqs/.nixfiles/users/modules/zsh.nix"
        "/home/basqs/.nixfiles/users/modules/emacs.nix"
        "/home/basqs/Documents/org/org-agenda.org"
        "/home/basqs/.nixfiles/users/configs/emacs/var/bookmark-default.el"
        "/home/basqs/.config/emacs/var/bookmark-default.el"
        "/home/basqs/.nixfiles/users/configs/emacs/emacs.org"
        "/home/basqs/.config/emacs/emacs.org"
        "/home/basqs/Documents/Go/goProgrammingTutorial/routine.go"
        "/home/basqs/Documents/Go/goProgrammingTutorial/server.go"
        "/home/basqs/Documents/Go/goProgrammingTutorial/io.go"
        "/home/basqs/Documents/Go/goProgrammingTutorial/strings.go"
        "/home/basqs/Documents/Go/goProgrammingTutorial/shape.go"
        "/home/basqs/Documents/Go/goProgrammingTutorial/structs.go"
        "/home/basqs/Documents/Go/goProgrammingTutorial/pointers.go"
        "/home/basqs/Documents/Go/goProgrammingTutorial/division.go"
        "/home/basqs/Documents/Go/goProgrammingTutorial/recursion.go"
        "/home/basqs/Documents/Go/goProgrammingTutorial/closures.go"
        "/home/basqs/Documents/Go/goProgrammingTutorial/func.go"
        "/home/basqs/Documents/Go/goProgrammingTutorial/maps.go"
        "/home/basqs/Documents/Go/goProgrammingTutorial/slice.go"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
