;;; Automatically generated by ‘recentf’ on Thu Feb 17 17:52:50 2022.

(setq recentf-list
      '(
        "/home/basqs/Docs/org/org-agenda.org"
        "/home/basqs/.nixfiles/users/configs/emacs/var/bookmark-default.el"
        "/home/basqs/.config/emacs/var/bookmark-default.el"
        "/home/basqs/Docs/escola/2ano/trabalho-historia.org"
        "/home/basqs/Docs/Prog/Go/theGoProgrammingLanguage/1.org"
        "/home/basqs/.nixfiles/users/configs/emacs/emacs.org"
        "/home/basqs/.config/emacs/emacs.org"
        "/home/basqs/.nixfiles/users/modules/zathura.nix"
        "/home/basqs/Docs/Prog/C/convert temperatures/convert.c"
        "/home/basqs/Docs/Prog/Zig/Hello/hello.zig"
        "/home/basqs/Docs/Prog/Zig/test.zig"
        "/home/basqs/Docs/Prog/rust/shell/main.rs"
        "/home/basqs/Docs/Prog/Go/shell/main.go"
        "/home/basqs/.nixfiles/users/home.nix"
        "/home/basqs/.nixfiles/flake.nix"
        "/home/basqs/Docs/escola/2ano/cadernos.org"
        "/tmp/.nnndsSn1p"
        "/home/basqs/Docs/escola/2ano/2022_listaem_2em-1.pdf"
        "/home/basqs/sites.org"
        "/home/basqs/.nixfiles/users/modules/desktop.nix"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
