;;; Automatically generated by ‘recentf’ on Fri Jan 21 19:37:36 2022.

(setq recentf-list
      '(
        "/home/basqs/.nixfiles/users/configs/emacs/emacs.org"
        "/home/basqs/.emacs.d/emacs.org"
        "/home/basqs/Documents/org/org-agenda.org"
        "/home/basqs/.emacs.d/var/bookmark-default.el"
        "/home/basqs/.nixfiles/users/modules/emacs.nix"
        "/home/basqs/Documents/Scheme/sicp.org"
        "/home/basqs/.nixfiles/users/modules/desktop.nix"
        "/home/basqs/.nvidia-settings-rc"
        "/home/basqs/.nixfiles/users/home.nix"
        "/home/basqs/.emacs.d/init.el"
        "/home/basqs/.nixfiles/system/configuration.nix"
        "/home/basqs/.nixfiles/users/modules/git.nix"
        "/home/basqs/.nixfiles/README.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
