;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(consult--theme-history extended-command-history evil-ex-history file-name-history))
(setq consult--theme-history '("atom-one-dark"))
(setq extended-command-history '("consult-theme"))
(setq evil-ex-history '(#("w" 0 1 (ex-index 1))))
(setq file-name-history '("~/.nixfiles/users/modules/desktop.nix" "~/.nixfiles/flake.nix" "~/.nixfiles/system/hardware-configuration.nix" "~/.nixfiles/system/configuration.nix" "~/.nixfiles/system/hardware-configuration.nix" "~/.nixfiles/system/configuration.nix" "~/Documents/org/org-agenda.org" "~/.nixfiles/users/configs/emacs/var/bookmark-default.el" "~/.config/emacs/var/bookmark-default.el" "~/Documents/Go/goProgrammingTutorial/routine.go" "~/Documents/Go/goProgrammingTutorial/server.go" "~/Documents/Go/goProgrammingTutorial/io.go" "~/Documents/Go/goProgrammingTutorial/strings.go" "~/Documents/Go/goProgrammingTutorial/shape.go" "~/Documents/Go/goProgrammingTutorial/structs.go" "~/Documents/Go/goProgrammingTutorial/pointers.go" "~/Documents/Go/goProgrammingTutorial/division.go" "~/Documents/Go/goProgrammingTutorial/recursion.go" "~/Documents/Go/goProgrammingTutorial/closures.go" "~/Documents/Go/goProgrammingTutorial/func.go" "~/Documents/Go/goProgrammingTutorial/maps.go" "~/Documents/Go/goProgrammingTutorial/slice.go" "~/Documents/Go/goProgrammingTutorial/array.go" "~/Documents/Go/goProgrammingTutorial/for.go" "~/Documents/Go/goProgrammingTutorial/operators.go" "~/Documents/Go/goProgrammingTutorial/main.go"))
(setq evil-jumps-history '((228 "/home/basqs/.nixfiles/flake.nix")))
