;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(evil-ex-history))
(setq evil-ex-history '(#("q!" 0 1 (ex-index 1) 1 2 (ex-index 2))))
(setq evil-jumps-history 'nil)
