;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(file-name-history evil-ex-history extended-command-history))
(setq file-name-history '("~/.nixfiles/users/modules/wayland.nix" "~/Docs/escola/2ano/trabalho-historia.org" "~/Docs/org/org-agenda.org" "~/.nixfiles/users/configs/emacs/var/bookmark-default.el" "~/.config/emacs/var/bookmark-default.el" "~/Docs/Prog/Go/theGoProgrammingLanguage/1.org" "~/.nixfiles/users/configs/emacs/emacs.org" "~/.config/emacs/emacs.org" "~/.nixfiles/users/modules/zathura.nix" "~/Docs/Prog/C/convert temperatures/convert.c" "~/Docs/Prog/Zig/Hello/hello.zig" "~/Docs/Prog/Zig/test.zig" "~/Docs/Prog/rust/shell/main.rs" "~/Docs/Prog/Go/shell/main.go" "~/.nixfiles/users/home.nix" "~/.nixfiles/flake.nix" "~/Docs/escola/2ano/cadernos.org" "/tmp/.nnndsSn1p" "~/Docs/escola/2ano/2022_listaem_2em-1.pdf" "~/sites.org" "~/.nixfiles/users/modules/desktop.nix"))
(setq evil-ex-history '(#("w" 0 1 (ex-index 1))))
(setq evil-jumps-history 'nil)
