# tokyo night

## [colors.bright]
## black = "#444b6a"
## blue = "#7da6ff"
## cyan = "#0db9d7"
## green = "#b9f27c"
## magenta = "#bb9af7"
## red = "#ff7a93"
## white = "#acb0d0"
## yellow = "#ff9e64"
##
## [colors.normal]
## black = "#32344a"
## blue = "#7aa2f7"
## cyan = "#449dab"
## green = "#9ece6a"
## magenta = "#ad8ee6"
## red = "#f7768e"
## white = "#787c99"
## yellow = "#e0af68"
##
## [colors.primary]
## background = "#1a1b26"
## foreground = "#a9b1d6"


# Colors (Solarized Osaka)
# Source https://github.com/craftzdog/solarized-osaka.nvim

## # Default colors
## [colors.primary]
## background = '#001a1d'
## foreground = '#839496'
##
## # Normal colors
## [colors.normal]
## black   = '#073642'
## red     = '#dc322f'
## green   = '#859900'
## yellow  = '#b58900'
## blue    = '#268bd2'
## magenta = '#d33682'
## cyan    = '#2aa198'
## white   = '#eee8d5'
##
## # Bright colors
## [colors.bright]
## black   = '#4c4c4c'
## red     = '#cb4b16'
## green   = '#586e75'
## yellow  = '#657b83'
## blue    = '#839496'
## magenta = '#6c71c4'
## cyan    = '#93a1a1'
## white   = '#fdf6e3'

## # Colors (Solarized Light)
## # Default colors
## [colors.primary]
## background = '#fdf6e3'
## foreground = '#586e75'
##
## # Normal colors
## [colors.normal]
## black   = '#073642'
## red     = '#dc322f'
## green   = '#859900'
## yellow  = '#b58900'
## blue    = '#268bd2'
## magenta = '#d33682'
## cyan    = '#2aa198'
## white   = '#eee8d5'
##
## # Bright colors
## [colors.bright]
## black   = '#002b36'
## red     = '#cb4b16'
## green   = '#586e75'
## yellow  = '#657b83'
## blue    = '#839496'
## magenta = '#6c71c4'
## cyan    = '#93a1a1'
## white   = '#fdf6e3'

# Colors (Solarized Dark)

# # Default colors
# [colors.primary]
# background = '#002b36'
# foreground = '#839496'
#
# # Normal colors
# [colors.normal]
# black   = '#073642'
# red     = '#dc322f'
# green   = '#859900'
# yellow  = '#b58900'
# blue    = '#268bd2'
# magenta = '#d33682'
# cyan    = '#2aa198'
# white   = '#eee8d5'
#
# # Bright colors
# [colors.bright]
# black   = '#586e75'
# red     = '#cb4b16'
# green   = '#586e75'
# yellow  = '#657b83'
# blue    = '#839496'
# magenta = '#6c71c4'
# cyan    = '#93a1a1'
# white   = '#fdf6e3'


[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'


[cursor.style]
blinking = "on"

[font]
size = 15.0

[font.normal]
family = "Iosevka"

[[keyboard.bindings]]
key = "Comma"
mods = "Command"

[keyboard.bindings.command]
args = ["-c", "open ~/.config/alacritty/alacritty.yml"]
program = "sh"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[window]
decorations = "Transparent"
option_as_alt = "Both"
