#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
## start_audio () {
##     /usr/bin/pipewire &
##     /usr/bin/pipewire-pulse &
##     /usr/bin/wireplumber &
##     }
## start_audio &

riverctl map normal Super Return spawn 'kitty'

riverctl map normal Super Space spawn "rofi -show drun"

# riverctl map normal Super Space spawn "bemenu-run -i -p '' --fn 'IosevkaNerdFont 14' --hb '#ebdbb2' --hf '#282828' --nb '#282828' --nf '#ebdbb2' --tb '#282828' --tf '#ebdbb2' --ab '#282828' --af '#ebdbb2' --cb '#282828' --cf '#ebdbb2' --fb '#282828' --ff '#ebdbb2' --fbb '#282828' --fbf '#ebdbb2' -l 10 -W 0.5"

riverctl map normal Super+Shift L spawn "swaylock --screenshots --clock --indicator --indicator-radius 100 --indicator-thickness 7 --effect-blur 7x5  --effect-vignette 0.5:0.5 --ring-color 444b6a --key-hl-color a9b1d6 --line-color 00000000 --inside-color 1a1b2688 --separator-color 00000000 --text-color a9b1d6 --grace 2 --fade-in 0.2 --font IosevkaNerdFont"

# Super+Q to close the focused view
riverctl map normal Super Q close

# Super+Shift+E to exit river
riverctl map normal Super+Shift Q exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Move cursor to different display when focus
riverctl set-cursor-warp on-output-change

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous
riverctl map normal Super+Control H send-to-output previous
riverctl map normal Super+Control L send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
#riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super+Shift W spawn "kill waybar && waybar"
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift M send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift N send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

riverctl focus-follows-cursor normal

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super Tab focus-previous-tags

# Super+Space to toggle float
riverctl map normal Super T toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
#for mode in normal locked
#do
# Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
riverctl map normal None XF86AudioRaiseVolume  spawn 'pulsemixer --change-volume +5'
riverctl map normal None XF86AudioLowerVolume  spawn 'pulsemixer --change-volume -5'
riverctl map normal None XF86AudioMute         spawn 'pulsemixer --toggle-mute'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map normal None XF86MonBrightnessUp   spawn 'brightnessctl -c backlight set +5%'
    riverctl map normal None XF86MonBrightnessDown spawn 'brightnessctl -c backlight set 5%-'
    #done

riverctl map normal None Print spawn 'grim ~/Pictures/screenshots/$(date "+%Y-%d-%m-%H:%M:%S").png'
riverctl map normal Shift Print spawn 'slurp | grim -g - ~/Pictures/screenshots/$(date "+%Y-%d-%m-%H:%M").png'
riverctl map normal Super S spawn 'slurp | grim -g - - | wl-copy'

# Set background and border color
riverctl background-color 0x1a1b26
riverctl border-color-focused 0xa9b1d6
riverctl border-color-unfocused 0x1a1b26

# Set keyboard repeat rate
riverctl set-repeat 50 300

## # Make all views with an app-id that starts with "float" and title "foo" start floating.
## riverctl rule-add -app-id 'float*' -title 'foo' float
##
## # Make all views with app-id "bar" and any title use client-side decorations
## riverctl rule-add -app-id "bar" csd

riverctl default-attach-mode bottom

riverctl  keyboard-layout br

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init spawnutable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 -main-ratio 0.5 &

# gnome_schema="org.gnome.desktop.interface"
# gsettings set $gnome-schema gtk-theme 'Tokyonight-Light' &
# gsettings set $gnome-schema icon-theme 'Tokyonight-light' &
# gsettings set $gnome-schema font-name 'IosevkaNerdFont' &


riverctl spawn 'swaybg -m fill -i ~/Pictures/wallpapers/1694053508715626.png'
riverctl spawn 'wlsunset -l -20 -L -44'
riverctl spawn 'emacs --daemon'
riverctl spawn 'waybar'
riverctl spawn 'swaync'
riverctl spawn 'if [[ $(wlr-randr --json | jq ".[0].model" -r) = "ARZOPA" ]]; then wlr-randr --output $(wlr-randr --json | jq ".[0].name" -r) --mode 1920x1080 --transform 90; fi'
riverctl input pointer-1267-12691-ELAN06C7:00_04F3:3193_Touchpad tap enabled &


riverctl map normal Super A spawn "emacsclient -c -n"
riverctl map normal Super+Shift T spawn "emacsclient -c -e '(progn (toggle-frame-maximized) (org-todo-list))'"
riverctl map normal Super+Shift A spawn "emacsclient -c -e '(progn (toggle-frame-maximized) (org-agenda-list))'"
riverctl map normal Super E spawn "emacsclient --eval '(emacs-everywhere)'"
riverctl map normal Super P spawn "okular"
riverctl map normal Super+Shift P spawn "obsidian"
riverctl map normal Super+Shift F spawn "pcmanfm"
riverctl map normal Super O spawn "zen"
riverctl map normal Super+Shift O spawn "brave"
riverctl map normal Super+Shift W spawn "pkill waybar && waybar"
